### ISSUE TITLE
Fix NoClassDefFound error occurring due to the org.bstats.bukkit.Metrics class not being found

### ISSUE THREAD

**Issue by dmccoystephenson** [dmccoystephenson/my-RPKit#7]
## Problem
An error is being thrown at runtime while enabling the rpk-chat-bukkit module due to a class not being found. Other modules are not throwing this error, so this may be due to my modifications.

## Error Message
rpk-mc-server  | [00:43:11] [Server thread/ERROR]: Error occurred while enabling rpk-chat-bukkit v2.3.3-mc1.18-1 (Is it up to date?)
rpk-mc-server  | java.lang.NoClassDefFoundError: org/bstats/bukkit/Metrics
rpk-mc-server  |        at com.rpkit.chat.bukkit.RPKChatBukkit.onEnable(RPKChatBukkit.kt:84) ~[?:?]
rpk-mc-server  |        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]        
rpk-mc-server  |        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
rpk-mc-server  |        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
rpk-mc-server  |        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:518) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
rpk-mc-server  |        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:432) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
rpk-mc-server  |        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:612) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
rpk-mc-server  |        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
rpk-mc-server  |        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:263) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
rpk-mc-server  |        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1007) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
rpk-mc-server  |        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
rpk-mc-server  |        at java.lang.Thread.run(Thread.java:840) [?:?]
rpk-mc-server  | Caused by: java.lang.ClassNotFoundException: org.bstats.bukkit.Metrics
rpk-mc-server  |        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
rpk-mc-server  |        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
rpk-mc-server  |        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
rpk-mc-server  |        ... 12 more

**Comment by dmccoystephenson** [comment]
This was an issue with compilation. Using the provided dev container to compile the JAR worked just fine.
